In [ ]:
import pandas as pd

In [64]:
data = [[1, 100], [2, 200], [3, 300]]
employee = pd.DataFrame(data, columns=['Id', 'Salary']).astype({'Id':'Int64', 'Salary':'Int64'})
N = 2
N_string = str(N)

In [83]:
employee['rank'] = employee['Salary'].rank(method = 'dense', ascending = False)
nth_highest_salary = employee[employee['rank']==N][['Salary']]
resultado = pd.DataFrame({'getNthHighestSalary('+N_string+')':[None if len(nth_highest_salary) == 0 else nth_highest_salary['Salary'].iloc[0]]})
resultado

   getNthHighestSalary(2)
0                     200